version: "3.9"
services:
  api:
    build: .
    image: msk-io:latest
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
    command: ["python", "-m", "uvicorn", "msk_io.api:app", "--host", "0.0.0.0", "--port", "8000"]
